[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
[".oh-my-zsh/custom/plugins/zsh-vi-mode"]
    type = "git-repo"
    url = "https://github.com/jeffreytse/zsh-vi-mode"
[".oh-my-zsh/custom/plugins/zsh-completions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-completions"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
